services:
  backend:
    build:
      context: ./varsel
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - varsel-network
    develop:
      watch:
        - action: rebuild
          path: ./varsel/src
        - action: rebuild
          path: ./varsel/pom.xml

  frontend:
    build:
      context: ./varsel-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - varsel-network
    develop:
      watch:
        - action: rebuild
          path: ./varsel-frontend/src
        - action: rebuild
          path: ./varsel-frontend/package.json

networks:
  varsel-network:
    driver: bridge